In [1]:
# importing the numpy modules
import numpy as np

In [3]:
# Matrix Addition :  add the numbers in the matching positions:
A = np.array([[3,8],[4,6]])
B = np.array([[4,0],[1,-9]])

A + B

array([[ 7,  8],
       [ 5, -3]])

In [4]:
# MAtrix Subtarction: subtract the numbers in the matching positions:
A = np.array([[3,8],[4,6]])
B = np.array([[4,0],[1,-9]])

A - B

array([[-1,  8],
       [ 3, 15]])

In [6]:
# Multiplying by a constant (Scalar Multiplication)
2 * B

array([[  8,   0],
       [  2, -18]])

In [9]:
# Multiplication of Matrix with another Matrix : But to multiply a matrix by another matrix we need to do the "dot product" of rows and columns
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])